name: Django Tests
on:
  push:
    branches: 
      - jenkins
  
  pull_request:
    branchs:
      -jenkins
  
  # on:
  #   schedule:
  #     - cron: '*/15 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
          python manage.py makemigrations
          python manage.py migrate
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test
                
    - name: Run server
      run: |
        python manage.py runserver -d
    - name: Custom Pytests
      run: |
        pytest test_cases

